name: client

services:     
  main:
    build:
      context: .
      target: development
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    working_dir: /home/client/workspace
    volumes:
      - type: bind
        source: .
        target: /home/client/workspace
    command: sleep infinity
    tty: true
    stdin_open: true
    init: true
    user: ${UID:-1000}:${GID:-1000}
